namespace TfsServicesExpertBlog.DataContracts.FullyExpandedWorkItem
{
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator

    using Newtonsoft.Json;
    public partial class FullyExpandedWorkItem
    {
        public class Fields2
        {

            [JsonProperty("System.Id")]
            public int SystemId;

            [JsonProperty("System.AreaId")]
            public int SystemAreaId;

            [JsonProperty("System.AreaPath")]
            public string SystemAreaPath;

            [JsonProperty("System.NodeName")]
            public string SystemNodeName;

            [JsonProperty("System.TeamProject")]
            public string SystemTeamProject;

            [JsonProperty("System.AreaLevel1")]
            public string SystemAreaLevel1;

            [JsonProperty("System.Rev")]
            public int SystemRev;

            [JsonProperty("System.AuthorizedDate")]
            public string SystemAuthorizedDate;

            [JsonProperty("System.RevisedDate")]
            public string SystemRevisedDate;

            [JsonProperty("System.IterationId")]
            public int SystemIterationId;

            [JsonProperty("System.IterationPath")]
            public string SystemIterationPath;

            [JsonProperty("System.IterationLevel1")]
            public string SystemIterationLevel1;

            [JsonProperty("System.WorkItemType")]
            public string SystemWorkItemType;

            [JsonProperty("System.State")]
            public string SystemState;

            [JsonProperty("System.Reason")]
            public string SystemReason;

            [JsonProperty("System.CreatedDate")]
            public string SystemCreatedDate;

            [JsonProperty("System.CreatedBy")]
            public string SystemCreatedBy;

            [JsonProperty("System.ChangedDate")]
            public string SystemChangedDate;

            [JsonProperty("System.ChangedBy")]
            public string SystemChangedBy;

            [JsonProperty("System.AuthorizedAs")]
            public string SystemAuthorizedAs;

            [JsonProperty("System.PersonId")]
            public int SystemPersonId;

            [JsonProperty("System.Watermark")]
            public int SystemWatermark;

            [JsonProperty("System.Title")]
            public string SystemTitle;

            [JsonProperty("Microsoft.VSTS.Scheduling.Effort")]
            public int MicrosoftVSTSSchedulingEffort;

            [JsonProperty("WEF_6CB513B6E70E43499D9FC94E5BBFB784_System.ExtensionMarker")]
            public bool WEF6CB513B6E70E43499D9FC94E5BBFB784SystemExtensionMarker;

            [JsonProperty("WEF_6CB513B6E70E43499D9FC94E5BBFB784_Kanban.Column")]
            public string WEF6CB513B6E70E43499D9FC94E5BBFB784KanbanColumn;

            [JsonProperty("System.Description")]
            public string SystemDescription;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class Attributes2
        {

            [JsonProperty("isLocked")]
            public bool IsLocked;

            [JsonProperty("comment")]
            public string Comment;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class Relation
        {

            [JsonProperty("rel")]
            public string Rel;

            [JsonProperty("url")]
            public string Url;

            [JsonProperty("attributes")]
            public Attributes2 Attributes;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class Self2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class WorkItemUpdates2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class WorkItemRevisions2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class WorkItemHistory2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class Html2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class WorkItemType2
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class Fields3
        {

            [JsonProperty("href")]
            public string Href;
        }
    }

    public partial class FullyExpandedWorkItem
    {
        public class Links
        {

            [JsonProperty("self")]
            public Self2 Self;

            [JsonProperty("workItemUpdates")]
            public WorkItemUpdates2 WorkItemUpdates;

            [JsonProperty("workItemRevisions")]
            public WorkItemRevisions2 WorkItemRevisions;

            [JsonProperty("workItemHistory")]
            public WorkItemHistory2 WorkItemHistory;

            [JsonProperty("html")]
            public Html2 Html;

            [JsonProperty("workItemType")]
            public WorkItemType2 WorkItemType;

            [JsonProperty("fields")]
            public Fields3 Fields;
        }
    }

    public partial class FullyExpandedWorkItem
    {

        [JsonProperty("id")]
        public int Id;

        [JsonProperty("rev")]
        public int Rev;

        [JsonProperty("fields")]
        public Fields2 Fields;

        [JsonProperty("relations")]
        public Relation[] Relations;

        [JsonProperty("_links")]
        public Links Links2;

        [JsonProperty("url")]
        public string Url;
    }

}
