using DataContracts.WorkItemDataTypes;
using Newtonsoft.Json;

namespace TfsServicesExpertBlog.DataContracts
{
    
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator

    public class WorkItem
    {
        public WorkItem()
        {
            this.Fields = new Fields();
            this.Links = new Links();
        }

        [JsonProperty("id")]
        public int Id
        {
            get; set;
        }

        [JsonProperty("rev")]
        public int Rev
        {
            get; set;
        }

        [JsonProperty("fields")]
        public Fields Fields
        {
            get; set;
        }

        [JsonProperty("_links")]
        public Links Links
        {
            get; set;
        }

        [JsonProperty("url")]
        public string Url
        {
            get; set;
        }
    }

}

namespace DataContracts.WorkItemDataTypes
{

    public class Fields
    {

        [JsonProperty("System.AreaPath")]
        public string SystemAreaPath { get; set; }

        [JsonProperty("System.TeamProject")]
        public string SystemTeamProject { get; set; }

        [JsonProperty("System.IterationPath")]
        public string SystemIterationPath { get; set; }

        [JsonProperty("System.WorkItemType")]
        public string SystemWorkItemType { get; set; }

        [JsonProperty("System.State")]
        public string SystemState { get; set; }

        [JsonProperty("System.Reason")]
        public string SystemReason { get; set; }

        [JsonProperty("System.CreatedDate")]
        public string SystemCreatedDate { get; set; }

        [JsonProperty("System.CreatedBy")]
        public string SystemCreatedBy { get; set; }

        [JsonProperty("System.ChangedDate")]
        public string SystemChangedDate { get; set; }

        [JsonProperty("System.ChangedBy")]
        public string SystemChangedBy { get; set; }

        [JsonProperty("System.Title")]
        public string SystemTitle { get; set; }

        [JsonProperty("System.BoardColumn")]
        public string SystemBoardColumn { get; set; }

        [JsonProperty("Microsoft.VSTS.Common.BacklogPriority")]
        public double MicrosoftVSTSCommonBacklogPriority { get; set; }

        [JsonProperty("Microsoft.VSTS.Scheduling.Effort")]
        public double MicrosoftVSTSSchedulingEffort { get; set; }

        [JsonProperty("WEF_23DEB0A7D2DB4749A5A59C039AAB1085_Kanban.Column")]
        public string WEF23DEB0A7D2DB4749A5A59C039AAB1085KanbanColumn { get; set; }
    }

    public class Self
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class WorkItemUpdates
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class WorkItemRevisions
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class WorkItemHistory
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Html
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class WorkItemType
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Fields2
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Links
    {

        [JsonProperty("self")]
        public Self Self { get; set; }

        [JsonProperty("workItemUpdates")]
        public WorkItemUpdates WorkItemUpdates { get; set; }

        [JsonProperty("workItemRevisions")]
        public WorkItemRevisions WorkItemRevisions { get; set; }

        [JsonProperty("workItemHistory")]
        public WorkItemHistory WorkItemHistory { get; set; }

        [JsonProperty("html")]
        public Html Html { get; set; }

        [JsonProperty("workItemType")]
        public WorkItemType WorkItemType { get; set; }

        [JsonProperty("fields")]
        public Fields2 Fields { get; set; }
    }
}


