using DataContracts.WorkItemLinkDataTypes;
using Newtonsoft.Json;

namespace TfsServicesExpertBlog.DataContracts
{
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator


    public class WorkItemLink
    {

        [JsonProperty("rel")]
        public string Rel
        {
            get; set;
        }

        [JsonProperty("url")]
        public string Url
        {
            get; set;
        }

        [JsonProperty("attributes")]
        public Attributes Attributes
        {
            get; set;
        }
    }
}

namespace DataContracts.WorkItemLinkDataTypes
{

    public class Attributes
    {

        [JsonProperty("comment")]
        public string Comment { get; set; }
    }
}


