using Newtonsoft.Json;

namespace TfsServicesExpertBlog.DataContracts
{
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator
    
    namespace Example
    {
        public partial class WorkItemCreatedEvent
        {
            public class Message2
            {

                [JsonProperty("text")]
                public string Text { get; set; }

                [JsonProperty("html")]
                public string Html { get; set; }

                [JsonProperty("markdown")]
                public string Markdown { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class DetailedMessage2
            {

                [JsonProperty("text")]
                public string Text { get; set; }

                [JsonProperty("html")]
                public string Html { get; set; }

                [JsonProperty("markdown")]
                public string Markdown { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Fields2
            {

                [JsonProperty("System.AreaPath")]
                public string SystemAreaPath { get; set; }

                [JsonProperty("System.TeamProject")]
                public string SystemTeamProject { get; set; }

                [JsonProperty("System.IterationPath")]
                public string SystemIterationPath { get; set; }

                [JsonProperty("System.WorkItemType")]
                public string SystemWorkItemType { get; set; }

                [JsonProperty("System.State")]
                public string SystemState { get; set; }

                [JsonProperty("System.Reason")]
                public string SystemReason { get; set; }

                [JsonProperty("System.CreatedDate")]
                public string SystemCreatedDate { get; set; }

                [JsonProperty("System.CreatedBy")]
                public string SystemCreatedBy { get; set; }

                [JsonProperty("System.ChangedDate")]
                public string SystemChangedDate { get; set; }

                [JsonProperty("System.ChangedBy")]
                public string SystemChangedBy { get; set; }

                [JsonProperty("System.Title")]
                public string SystemTitle { get; set; }

                [JsonProperty("Microsoft.VSTS.Common.Priority")]
                public int MicrosoftVSTSCommonPriority { get; set; }

                [JsonProperty("Microsoft.VSTS.Common.StateChangeDate")]
                public string MicrosoftVSTSCommonStateChangeDate { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Attributes2
            {

                [JsonProperty("isLocked")]
                public bool IsLocked { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Relation
            {

                [JsonProperty("rel")]
                public string Rel { get; set; }

                [JsonProperty("url")]
                public string Url { get; set; }

                [JsonProperty("attributes")]
                public Attributes2 Attributes { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Self2
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class WorkItemUpdates2
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class WorkItemRevisions2
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class WorkItemHistory2
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Html2
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class WorkItemType2
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Fields3
            {

                [JsonProperty("href")]
                public string Href { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Links
            {

                [JsonProperty("self")]
                public Self2 Self { get; set; }

                [JsonProperty("workItemUpdates")]
                public WorkItemUpdates2 WorkItemUpdates { get; set; }

                [JsonProperty("workItemRevisions")]
                public WorkItemRevisions2 WorkItemRevisions { get; set; }

                [JsonProperty("workItemHistory")]
                public WorkItemHistory2 WorkItemHistory { get; set; }

                [JsonProperty("html")]
                public Html2 Html { get; set; }

                [JsonProperty("workItemType")]
                public WorkItemType2 WorkItemType { get; set; }

                [JsonProperty("fields")]
                public Fields3 Fields { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Resource2
            {

                [JsonProperty("id")]
                public int Id { get; set; }

                [JsonProperty("rev")]
                public int Rev { get; set; }

                [JsonProperty("fields")]
                public Fields2 Fields { get; set; }

                [JsonProperty("relations")]
                public Relation[] Relations { get; set; }

                [JsonProperty("_links")]
                public Links Links { get; set; }

                [JsonProperty("url")]
                public string Url { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Collection2
            {

                [JsonProperty("id")]
                public string Id { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Account2
            {

                [JsonProperty("id")]
                public string Id { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class Project2
            {

                [JsonProperty("id")]
                public string Id { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {
            public class ResourceContainers2
            {

                [JsonProperty("collection")]
                public Collection2 Collection { get; set; }

                [JsonProperty("account")]
                public Account2 Account { get; set; }

                [JsonProperty("project")]
                public Project2 Project { get; set; }
            }
        }

        public partial class WorkItemCreatedEvent
        {

            [JsonProperty("subscriptionId")]
            public string SubscriptionId { get; set; }

            [JsonProperty("notificationId")]
            public int NotificationId { get; set; }

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("eventType")]
            public string EventType { get; set; }

            [JsonProperty("publisherId")]
            public string PublisherId { get; set; }

            [JsonProperty("message")]
            public Message2 Message { get; set; }

            [JsonProperty("detailedMessage")]
            public DetailedMessage2 DetailedMessage { get; set; }

            [JsonProperty("resource")]
            public Resource2 Resource { get; set; }

            [JsonProperty("resourceVersion")]
            public string ResourceVersion { get; set; }

            [JsonProperty("resourceContainers")]
            public ResourceContainers2 ResourceContainers { get; set; }

            [JsonProperty("createdDate")]
            public string CreatedDate { get; set; }
        }

    }
}
