// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using DataContracts.WorkItemChangedEventJsonTypes;
using Newtonsoft.Json;

namespace DataContracts.WorkItemChangedEventJsonTypes
{

    public class Message
    {

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("markdown")]
        public string Markdown { get; set; }
    }

    public class DetailedMessage
    {

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("markdown")]
        public string Markdown { get; set; }
    }

    public class RevisedBy
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class SystemRev
    {

        [JsonProperty("oldValue")]
        public int OldValue { get; set; }

        [JsonProperty("newValue")]
        public int NewValue { get; set; }
    }

    public class SystemAuthorizedDate
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class SystemRevisedDate
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class SystemState
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class SystemReason
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class SystemChangedDate
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class SystemWatermark
    {

        [JsonProperty("oldValue")]
        public int OldValue { get; set; }

        [JsonProperty("newValue")]
        public int NewValue { get; set; }
    }

    public class SystemBoardColumn
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class WEF23DEB0A7D2DB4749A5A59C039AAB1085KanbanColumn
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class WEF1BADAD1758584DD1B1E7E026133F841DKanbanColumn
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class WEF41D18D3C323846EBA69D6642B08D35D3KanbanColumn
    {

        [JsonProperty("oldValue")]
        public string OldValue { get; set; }

        [JsonProperty("newValue")]
        public string NewValue { get; set; }
    }

    public class Fields
    {

        [JsonProperty("System.Rev")]
        public SystemRev SystemRev { get; set; }

        [JsonProperty("System.AuthorizedDate")]
        public SystemAuthorizedDate SystemAuthorizedDate { get; set; }

        [JsonProperty("System.RevisedDate")]
        public SystemRevisedDate SystemRevisedDate { get; set; }

        [JsonProperty("System.State")]
        public SystemState SystemState { get; set; }

        [JsonProperty("System.Reason")]
        public SystemReason SystemReason { get; set; }

        [JsonProperty("System.ChangedDate")]
        public SystemChangedDate SystemChangedDate { get; set; }

        [JsonProperty("System.Watermark")]
        public SystemWatermark SystemWatermark { get; set; }

        [JsonProperty("System.BoardColumn")]
        public SystemBoardColumn SystemBoardColumn { get; set; }

        [JsonProperty("WEF_23DEB0A7D2DB4749A5A59C039AAB1085_Kanban.Column")]
        public WEF23DEB0A7D2DB4749A5A59C039AAB1085KanbanColumn WEF23DEB0A7D2DB4749A5A59C039AAB1085KanbanColumn { get; set; }

        [JsonProperty("WEF_1BADAD1758584DD1B1E7E026133F841D_Kanban.Column")]
        public WEF1BADAD1758584DD1B1E7E026133F841DKanbanColumn WEF1BADAD1758584DD1B1E7E026133F841DKanbanColumn { get; set; }

        [JsonProperty("WEF_41D18D3C323846EBA69D6642B08D35D3_Kanban.Column")]
        public WEF41D18D3C323846EBA69D6642B08D35D3KanbanColumn WEF41D18D3C323846EBA69D6642B08D35D3KanbanColumn { get; set; }
    }

    public class Self
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class WorkItemUpdates
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Parent
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Links
    {

        [JsonProperty("self")]
        public Self Self { get; set; }

        [JsonProperty("workItemUpdates")]
        public WorkItemUpdates WorkItemUpdates { get; set; }

        [JsonProperty("parent")]
        public Parent Parent { get; set; }
    }

    public class Fields2
    {

        [JsonProperty("System.AreaPath")]
        public string SystemAreaPath { get; set; }

        [JsonProperty("System.TeamProject")]
        public string SystemTeamProject { get; set; }

        [JsonProperty("System.IterationPath")]
        public string SystemIterationPath { get; set; }

        [JsonProperty("System.WorkItemType")]
        public string SystemWorkItemType { get; set; }

        [JsonProperty("System.State")]
        public string SystemState { get; set; }

        [JsonProperty("System.Reason")]
        public string SystemReason { get; set; }

        [JsonProperty("System.CreatedDate")]
        public string SystemCreatedDate { get; set; }

        [JsonProperty("System.CreatedBy")]
        public string SystemCreatedBy { get; set; }

        [JsonProperty("System.ChangedDate")]
        public string SystemChangedDate { get; set; }

        [JsonProperty("System.ChangedBy")]
        public string SystemChangedBy { get; set; }

        [JsonProperty("System.Title")]
        public string SystemTitle { get; set; }

        [JsonProperty("System.BoardColumn")]
        public string SystemBoardColumn { get; set; }

        [JsonProperty("System.BoardColumnDone")]
        public bool SystemBoardColumnDone { get; set; }

        [JsonProperty("Microsoft.VSTS.Common.BacklogPriority")]
        public double MicrosoftVSTSCommonBacklogPriority { get; set; }

        [JsonProperty("Microsoft.VSTS.Common.Priority")]
        public int MicrosoftVSTSCommonPriority { get; set; }

        [JsonProperty("WEF_23DEB0A7D2DB4749A5A59C039AAB1085_Kanban.Column")]
        public string WEF23DEB0A7D2DB4749A5A59C039AAB1085KanbanColumn { get; set; }

        [JsonProperty("WEF_23DEB0A7D2DB4749A5A59C039AAB1085_Kanban.Column.Done")]
        public bool WEF23DEB0A7D2DB4749A5A59C039AAB1085KanbanColumnDone { get; set; }

        [JsonProperty("Microsoft.VSTS.Common.ValueArea")]
        public string MicrosoftVSTSCommonValueArea { get; set; }

        [JsonProperty("WEF_1BADAD1758584DD1B1E7E026133F841D_Kanban.Column")]
        public string WEF1BADAD1758584DD1B1E7E026133F841DKanbanColumn { get; set; }

        [JsonProperty("WEF_1BADAD1758584DD1B1E7E026133F841D_Kanban.Column.Done")]
        public bool WEF1BADAD1758584DD1B1E7E026133F841DKanbanColumnDone { get; set; }

        [JsonProperty("WEF_41D18D3C323846EBA69D6642B08D35D3_Kanban.Column")]
        public string WEF41D18D3C323846EBA69D6642B08D35D3KanbanColumn { get; set; }

        [JsonProperty("WEF_41D18D3C323846EBA69D6642B08D35D3_Kanban.Column.Done")]
        public bool WEF41D18D3C323846EBA69D6642B08D35D3KanbanColumnDone { get; set; }
    }

    public class Attributes
    {

        [JsonProperty("isLocked")]
        public bool IsLocked { get; set; }
    }

    public class Relation
    {

        [JsonProperty("rel")]
        public string Rel { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("attributes")]
        public Attributes Attributes { get; set; }
    }

    public class Self2
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class WorkItemRevisions
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Parent2
    {

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public class Links2
    {

        [JsonProperty("self")]
        public Self2 Self { get; set; }

        [JsonProperty("workItemRevisions")]
        public WorkItemRevisions WorkItemRevisions { get; set; }

        [JsonProperty("parent")]
        public Parent2 Parent { get; set; }
    }

    public class Revision
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("rev")]
        public int Rev { get; set; }

        [JsonProperty("fields")]
        public Fields2 Fields { get; set; }

        [JsonProperty("relations")]
        public Relation[] Relations { get; set; }

        [JsonProperty("_links")]
        public Links2 Links { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public class Resource
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("workItemId")]
        public int WorkItemId { get; set; }

        [JsonProperty("rev")]
        public int Rev { get; set; }

        [JsonProperty("revisedBy")]
        public RevisedBy RevisedBy { get; set; }

        [JsonProperty("revisedDate")]
        public string RevisedDate { get; set; }

        [JsonProperty("fields")]
        public Fields Fields { get; set; }

        [JsonProperty("_links")]
        public Links Links { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("revision")]
        public Revision Revision { get; set; }
    }

    public class Collection
    {

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public class Account
    {

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public class Project
    {

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public class ResourceContainers
    {

        [JsonProperty("collection")]
        public Collection Collection { get; set; }

        [JsonProperty("account")]
        public Account Account { get; set; }

        [JsonProperty("project")]
        public Project Project { get; set; }
    }

}

namespace Example
{

    public class WorkItemChangedEvent
    {

        [JsonProperty("subscriptionId")]
        public string SubscriptionId { get; set; }

        [JsonProperty("notificationId")]
        public int NotificationId { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("eventType")]
        public string EventType { get; set; }

        [JsonProperty("publisherId")]
        public string PublisherId { get; set; }

        [JsonProperty("message")]
        public Message Message { get; set; }

        [JsonProperty("detailedMessage")]
        public DetailedMessage DetailedMessage { get; set; }

        [JsonProperty("resource")]
        public Resource Resource { get; set; }

        [JsonProperty("resourceVersion")]
        public string ResourceVersion { get; set; }

        [JsonProperty("resourceContainers")]
        public ResourceContainers ResourceContainers { get; set; }

        [JsonProperty("createdDate")]
        public string CreatedDate { get; set; }
    }

}